//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace DataSchema
{
    #pragma warning disable // Disable all warnings

    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class Block
    {
    
        private StimulusProtocol _stimulus;
    
        private double _totalRuntime = 120D;
    
        private double _runThreshold = 100D;
    
        private double _decayTimestep = 0.1D;
    
        private double _runThresholdDecay = -1D;
    
        private double _haltProbability = 0.5D;
    
        private HaltProtocol _haltProtocol;
    
        /// <summary>
        /// The visual stimulus to use
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="stimulus")]
        [System.ComponentModel.DescriptionAttribute("The visual stimulus to use")]
        public StimulusProtocol Stimulus
        {
            get
            {
                return _stimulus;
            }
            set
            {
                _stimulus = value;
            }
        }
    
        /// <summary>
        /// How long (in seconds) this block should run for
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="totalRuntime")]
        [System.ComponentModel.DescriptionAttribute("How long (in seconds) this block should run for")]
        public double TotalRuntime
        {
            get
            {
                return _totalRuntime;
            }
            set
            {
                _totalRuntime = value;
            }
        }
    
        /// <summary>
        /// The value (in position units) to reach before a halt decision is applied
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="runThreshold")]
        [System.ComponentModel.DescriptionAttribute("The value (in position units) to reach before a halt decision is applied")]
        public double RunThreshold
        {
            get
            {
                return _runThreshold;
            }
            set
            {
                _runThreshold = value;
            }
        }
    
        /// <summary>
        /// On each timestep (in seconds) the runThresholdDecay is applied
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="decayTimestep")]
        [System.ComponentModel.DescriptionAttribute("On each timestep (in seconds) the runThresholdDecay is applied")]
        public double DecayTimestep
        {
            get
            {
                return _decayTimestep;
            }
            set
            {
                _decayTimestep = value;
            }
        }
    
        /// <summary>
        /// Distance to threshold is decayed by this amount (in position units) per decayTimestep
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="runThresholdDecay")]
        [System.ComponentModel.DescriptionAttribute("Distance to threshold is decayed by this amount (in position units) per decayTime" +
            "step")]
        public double RunThresholdDecay
        {
            get
            {
                return _runThresholdDecay;
            }
            set
            {
                _runThresholdDecay = value;
            }
        }
    
        /// <summary>
        /// The probability that a halt decision is made after a running threshold has been reached
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="haltProbability")]
        [System.ComponentModel.DescriptionAttribute("The probability that a halt decision is made after a running threshold has been r" +
            "eached")]
        public double HaltProbability
        {
            get
            {
                return _haltProbability;
            }
            set
            {
                _haltProbability = value;
            }
        }
    
        /// <summary>
        /// The halt protocol to use on a positive halt decision
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="haltProtocol")]
        [System.ComponentModel.DescriptionAttribute("The halt protocol to use on a positive halt decision")]
        public HaltProtocol HaltProtocol
        {
            get
            {
                return _haltProtocol;
            }
            set
            {
                _haltProtocol = value;
            }
        }
    
        public System.IObservable<Block> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(
                new Block
                {
                    Stimulus = _stimulus,
                    TotalRuntime = _totalRuntime,
                    RunThreshold = _runThreshold,
                    DecayTimestep = _decayTimestep,
                    RunThresholdDecay = _runThresholdDecay,
                    HaltProbability = _haltProbability,
                    HaltProtocol = _haltProtocol
                }));
        }
    }


    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class StimulusProtocol
    {
    
        private StimulusProtocolType _type = DataSchema.StimulusProtocolType.Grating;
    
        private double _spatialFrequency = 0.1D;
    
        private string _path = "";
    
        /// <summary>
        /// The type and parameters of the visual stimulus to use
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="type")]
        [System.ComponentModel.DescriptionAttribute("The type and parameters of the visual stimulus to use")]
        public StimulusProtocolType Type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }
    
        /// <summary>
        /// Spatial frequency for stimuli where this is a parameter
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="spatialFrequency")]
        [System.ComponentModel.DescriptionAttribute("Spatial frequency for stimuli where this is a parameter")]
        public double SpatialFrequency
        {
            get
            {
                return _spatialFrequency;
            }
            set
            {
                _spatialFrequency = value;
            }
        }
    
        /// <summary>
        /// Path to texture or video if required
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="path")]
        [System.ComponentModel.DescriptionAttribute("Path to texture or video if required")]
        public string Path
        {
            get
            {
                return _path;
            }
            set
            {
                _path = value;
            }
        }
    
        public System.IObservable<StimulusProtocol> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(
                new StimulusProtocol
                {
                    Type = _type,
                    SpatialFrequency = _spatialFrequency,
                    Path = _path
                }));
        }
    }


    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class HaltProtocol
    {
    
        private double _minumumDelay = 0.1D;
    
        private double _randomDelay = 0.5D;
    
        private double _haltTime = 2D;
    
        private double _haltGain = 0D;
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="minumumDelay")]
        public double MinumumDelay
        {
            get
            {
                return _minumumDelay;
            }
            set
            {
                _minumumDelay = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="randomDelay")]
        public double RandomDelay
        {
            get
            {
                return _randomDelay;
            }
            set
            {
                _randomDelay = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="haltTime")]
        public double HaltTime
        {
            get
            {
                return _haltTime;
            }
            set
            {
                _haltTime = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="haltGain")]
        public double HaltGain
        {
            get
            {
                return _haltGain;
            }
            set
            {
                _haltGain = value;
            }
        }
    
        public System.IObservable<HaltProtocol> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(
                new HaltProtocol
                {
                    MinumumDelay = _minumumDelay,
                    RandomDelay = _randomDelay,
                    HaltTime = _haltTime,
                    HaltGain = _haltGain
                }));
        }
    }


    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class VestibularVrSession
    {
    
        private Metadata _metadata;
    
        private System.Collections.Generic.List<Block> _blocks = new System.Collections.Generic.List<Block>();
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="metadata")]
        public Metadata Metadata
        {
            get
            {
                return _metadata;
            }
            set
            {
                _metadata = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="blocks")]
        public System.Collections.Generic.List<Block> Blocks
        {
            get
            {
                return _blocks;
            }
            set
            {
                _blocks = value;
            }
        }
    
        public System.IObservable<VestibularVrSession> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(
                new VestibularVrSession
                {
                    Metadata = _metadata,
                    Blocks = _blocks
                }));
        }
    }


    public enum StimulusProtocolType
    {
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="grating")]
        Grating = 0,
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="texture")]
        Texture = 1,
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="cloud")]
        Cloud = 2,
    }


    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class Metadata
    {
    
        private string _animalId = "";
    
        private string _rootPath = "";
    
        private double _runGain = 1D;
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="animalId")]
        public string AnimalId
        {
            get
            {
                return _animalId;
            }
            set
            {
                _animalId = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rootPath")]
        public string RootPath
        {
            get
            {
                return _rootPath;
            }
            set
            {
                _rootPath = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="runGain")]
        public double RunGain
        {
            get
            {
                return _runGain;
            }
            set
            {
                _runGain = value;
            }
        }
    
        public System.IObservable<Metadata> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(
                new Metadata
                {
                    AnimalId = _animalId,
                    RootPath = _rootPath,
                    RunGain = _runGain
                }));
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder().Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<Block> source)
        {
            return Process<Block>(source);
        }

        public System.IObservable<string> Process(System.IObservable<StimulusProtocol> source)
        {
            return Process<StimulusProtocol>(source);
        }

        public System.IObservable<string> Process(System.IObservable<HaltProtocol> source)
        {
            return Process<HaltProtocol>(source);
        }

        public System.IObservable<string> Process(System.IObservable<VestibularVrSession> source)
        {
            return Process<VestibularVrSession>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Metadata> source)
        {
            return Process<Metadata>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Block>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<StimulusProtocol>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<HaltProtocol>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<VestibularVrSession>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Metadata>))]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<VestibularVrSession>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder().Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}